version: "3.7"

services:
  django_web:
    build: .
    command: >
      ash -c "python manage.py migrate && gunicorn rishoGheichi.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rishogheichi
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8008:80
    depends_on:
      - django_web
  redis:
    image: redis:alpine
    volumes:
      - redis_val:/data
  celery:
    restart: always
    build:
      context: .
#      dockerfile: dokckerfile-name-alternative
#      args:
#        name : ashkan
    command: >
      ash -c "touch celery.log && touch celery_beat.log && celery -A rishoGheichi worker -l info &> celery.log & celery -A rishoGheichi beat -l info -S django &> celery_beat.log"
    volumes:
      - .:/app
    depends_on:
      - django_web
      - redis
volumes:
  postgres_data:
  static:
  media:
  redis_val: