# Generated by Django 3.2.6 on 2021-08-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userhayemoredealaghemardani'),
        ('course', '0002_alter_coursecategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='course.coursecategory', verbose_name='کتگوری درس'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='shakgham'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.mentor', verbose_name='مدرس دوره'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('d', 'deprecated'), ('f', 'finished'), ('i', 'inprogress')], default='i', max_length=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='salam', max_length=255, verbose_name='عنوان دوره'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
