# Generated by Django 3.2.6 on 2021-08-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210826_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseComments',
        ),
        migrations.AddField(
            model_name='course',
            name='commentable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course'),
        ),
    ]
