# Generated by Django 3.2.5 on 2021-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.CharField(blank=True, choices=[('p', 'positive'), ('n', 'negative')], max_length=1, null=True),
        ),
    ]
