# Generated by Django 3.2.5 on 2021-08-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
