# Generated by Django 3.2.6 on 2021-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userhayemoredealaghemardani'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhayemoredealaghemardani',
            options={'verbose_name': 'mardani_user', 'verbose_name_plural': 'mardani_users'},
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
