# Generated by Django 3.2.6 on 2021-09-28 15:30

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210831_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path),
        ),
    ]
