# Generated by Django 3.2.7 on 2021-09-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('nezam_pezeshki', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CoronaInforamtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('diabet', models.BooleanField()),
                ('feshar_khoon', models.BooleanField()),
                ('charbi_khoon', models.BooleanField()),
                ('talasemi', models.BooleanField()),
                ('tiroid', models.BooleanField()),
                ('sareee', models.BooleanField()),
                ('asm', models.BooleanField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doctor')),
            ],
        ),
    ]
