# Generated by Django 3.2.6 on 2021-08-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('modat_zaman', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=500)),
                ('maghta', models.CharField(choices=[('k', 'karshenasi'), ('a', 'arshad'), ('d', 'doctora'), ('p', 'pasa doctora')], max_length=1, verbose_name='مقطع تحصیلی')),
                ('grade', models.FloatField(validators=[resume.validations.validate_grade_education])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
